name: geziyorum
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.8.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Firebase Paketleri - Uyumlu sürümler
  firebase_core: ^2.32.0
  firebase_auth: ^4.20.0
  firebase_storage: ^11.7.7
  cloud_firestore: ^4.17.5

  # Diğer paketler
  shared_preferences: ^2.2.3
  cupertino_icons: ^1.0.8
  url_launcher: ^6.2.5
  uuid: ^4.3.3
  collection: ^1.18.0
  intl: ^0.19.0
  provider: ^6.1.5
  google_sign_in: ^6.2.1
  font_awesome_flutter: ^10.7.0
  image_picker: ^0.8.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
