// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBw7wkeiTK8Bu4atgcKBZIBAqbzvCuTb9A',
    appId: '1:298519641212:web:dc9ec0549ddd1953e69df9',
    messagingSenderId: '298519641212',
    projectId: 'geziyorumapp-fc74c',
    authDomain: 'geziyorumapp-fc74c.firebaseapp.com',
    storageBucket: 'geziyorumapp-fc74c.firebasestorage.app',
    measurementId: 'G-REL1S2595J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCFYKnJ5Q2H6AtajCZHCX_zNwhLp--X45U',
    appId: '1:298519641212:android:40386a816707a03ae69df9',
    messagingSenderId: '298519641212',
    projectId: 'geziyorumapp-fc74c',
    storageBucket: 'geziyorumapp-fc74c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJ7XP0in0yduSm72gc9rCQk2X7Qc2F1LE',
    appId: '1:298519641212:ios:7b4dfdc1bfb9c90be69df9',
    messagingSenderId: '298519641212',
    projectId: 'geziyorumapp-fc74c',
    storageBucket: 'geziyorumapp-fc74c.firebasestorage.app',
    iosBundleId: 'com.example.geziyorum',
  );
}
